"""
Database Module

Provides database models and access layer for YACLib Enhanced.
"""

from .models import (
    Base,
    Library,
    Folder,
    Comic,
    Cover,
    User,
    Session,
    ReadingProgress,
    Series,
    Collection,
    Favorite,
    Label,
    ComicLabel,
    ReadingList,
    ReadingListItem,
)

from .database import (
    Database,
    get_project_root,
    get_default_db_path,
    get_data_dir,
    get_library_data_dir,
    get_covers_dir,
    # Library operations
    create_library,
    get_library_by_id,
    get_library_by_path,
    get_library_by_path,
    get_all_libraries,
    update_library,
    delete_library,
    update_library_scan_status,
    update_library_series_tree_cache,
    # Comic operations
    create_comic,
    get_comic_by_id,
    get_comic_by_hash,
    get_comic_by_path_and_mtime,
    get_comics_in_library,
    get_all_comics_in_db,
    get_comics_in_folder,
    get_comics_in_folder_simple,
    get_sibling_comics,
    # Folder operations
    create_folder,
    get_folder_by_id,
    get_folder_by_path,
    get_folders_in_library,
    get_subfolders,
    get_or_create_root_folder,
    get_first_comic_recursive,
    # User operations
    get_user_by_username,
    get_user_by_id,
    # Session operations
    create_session,
    get_session_by_id,
    update_session_activity,
    cleanup_expired_sessions,
    # Statistics
    get_library_stats,
    # Reading Progress operations
    update_reading_progress,
    get_reading_progress,
    get_continue_reading,
    get_recently_completed,
    # Cover operations
    create_cover,
    get_cover,
    get_best_cover,
    delete_cover,
    # Favorites operations
    add_favorite,
    remove_favorite,
    get_user_favorites,
    is_favorite,
    # Labels/Tags operations
    create_label,
    get_label_by_id,
    get_labels_in_library,
    delete_label,
    add_label_to_comic,
    remove_label_from_comic,
    get_comics_with_label,
    get_comic_labels,
    # Reading Lists operations
    create_reading_list,
    get_reading_list_by_id,
    get_reading_lists_in_library,
    delete_reading_list,
    add_comic_to_reading_list,
    remove_comic_from_reading_list,
    get_reading_list_comics,
)

__all__ = [
    # Models
    'Base',
    'Library',
    'Folder',
    'Comic',
    'Cover',
    'User',
    'Session',
    'ReadingProgress',
    'Series',
    'Collection',
    'Favorite',
    'Label',
    'ComicLabel',
    'ReadingList',
    'ReadingListItem',
    # Database
    'Database',
    'get_project_root',
    'get_default_db_path',
    'get_data_dir',
    'get_library_data_dir',
    'get_covers_dir',
    # Operations
    'create_library',
    'get_library_by_id',
    'get_library_by_path',
    'get_library_by_path',
    'get_all_libraries',
    'update_library',
    'delete_library',
    'update_library_scan_status',
    'update_library_series_tree_cache',
    'create_comic',
    'get_comic_by_id',
    'get_comic_by_hash',
    'get_comic_by_path_and_mtime',
    'get_comics_in_library',
    'get_all_comics_in_db',
    'get_comics_in_folder',
    'get_comics_in_folder_simple',
    'get_sibling_comics',
    'create_folder',
    'get_folder_by_id',
    'get_folder_by_path',
    'get_folders_in_library',
    'get_subfolders',
    'get_or_create_root_folder',
    'get_first_comic_recursive',
    'get_user_by_username',
    'get_user_by_id',
    'create_session',
    'get_session_by_id',
    'update_session_activity',
    'cleanup_expired_sessions',
    'get_library_stats',
    'update_reading_progress',
    'get_reading_progress',
    'get_continue_reading',
    'get_recently_completed',
    'create_cover',
    'get_cover',
    'get_best_cover',
    'delete_cover',
    # Favorites
    'add_favorite',
    'remove_favorite',
    'get_user_favorites',
    'is_favorite',
    # Labels/Tags
    'create_label',
    'get_label_by_id',
    'get_labels_in_library',
    'delete_label',
    'add_label_to_comic',
    'remove_label_from_comic',
    'get_comics_with_label',
    'get_comic_labels',
    # Reading Lists
    'create_reading_list',
    'get_reading_list_by_id',
    'get_reading_lists_in_library',
    'delete_reading_list',
    'add_comic_to_reading_list',
    'remove_comic_from_reading_list',
    'get_reading_list_comics',
]
